# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6483d4fa7dbff378876b4683e34574feedfe25c9db0f8fd86bc059bf90d359638914f348131dbe4c58d422bf387ac08dd224bd6d55bc3ce73ca718ffcdb18b95

test:
  secret_key_base: cfd164b60c9c674eb9cf5765681eee01d43b674faaf64072e3135f88e719f8e82dce97c192c493f2bf7da2b08fb875f87131ba87ba36d414c499d74ae3ec8fc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
